covidform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('new_form/', views.create_covid, name='create'),
    path('edit_form/<int:covid_id>', views.update_covid, name='update'),
    path('delete_form/<int:covid_pk>', login_required(views.DeleteCovidView.as_view()), name='delete_form'),
    path('export/<int:covid_id>', views.export, name='export'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('', views.index, name='homepage'),
    path('search', views.search_tz, name='search'),
    path('search_date', views.search_date, name='search_date'),
    path('search_sticker', views.search_sticker, name='search_sticker'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.core.validators import RegexValidator


# Create your models here.


class CovidData(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    lab_code = models.CharField(max_length=5, default='41997')
    lab_desc = models.CharField(max_length=30, default='מעבדת אוניברסיטת תל אביב')
    ID_num = models.CharField(max_length=10, validators=[
            RegexValidator(
                regex='^[0-9]*$',
                message='ת"ז לא תקין - אנא הכנס רק מספרים',
            ),
        ])
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=1, choices=[('ז','זכר'),('נ','נקבה')])
    year_of_birth = models.CharField(max_length=4, choices=[(str(num),str(num)) for num in range(2020, 1919, -1)])
    year_of_sticker = models.CharField(max_length=4, default='2020')
    sticker_number = models.CharField(max_length=9)
    internal_code = models.CharField(max_length=2, null=True, blank=True, default='')
    internal_number = models.CharField(max_length=8, null=True, blank=True, default='')
    spec_code = models.CharField(max_length=30, default='RNA')
    spec_desc = models.CharField(max_length=150, default='חומר גנטי')
    method_code = models.CharField(max_length=4, default='qPCR')
    method_desc = models.CharField(max_length=30, default='אמפליפיקציה של חומר גנומי')
    section_code = models.CharField(max_length=4, null=True, blank=True, default='')
    section_desc = models.CharField(max_length=30, null=True, blank=True, default='')
    tested_code = models.CharField(max_length=9, default="259")
    tested_desc = models.CharField(max_length=30)
    take_date = models.DateField()
    get_date = models.DateField()
    result_date = models.DateField(default=timezone.now)
    result = models.CharField(max_length=30, null=True, default='', blank=True)
    remark = models.TextField(max_length=2000, default='', blank=True)
    id_type = models.IntegerField(choices=[(0, 'ת"ז ישראלי - 0'), (1, 'ת"ז ישראלי - 1'), (2, 'דרכון - 2'), (3, 'אחר - 3')])
    sender_code = models.IntegerField(default=0)
    sender_name = models.CharField(max_length=30, null=True, blank=True, default='')
    sender_full_name = models.CharField(max_length=100, null=True, blank=True, default='')
    result_test_corona = models.IntegerField(choices=[(1,'חיובי'), (0,'שלילי'), (2,'בעבודה'), (999,'לא בוצע')], null=True, blank=True)
    exported = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']


    def __str__(self):
        return f'Sticker Number: {self.sticker_number} Result date:{self.result_date}'
    

main/forms.py
from django import forms
from .models import CovidData
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from dal import autocomplete


class SignUpForm(UserCreationForm):
    key = forms.CharField(required=True, label='קוד הרשמה', help_text='על מנת לקבל קוד הרשמה נא ליצור קשר עם מנהל המערכת')
    first_name = forms.CharField(required=True, label='שם פרטי')
    last_name = forms.CharField(required=True, label='שם משפחה')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )
        labels = {
            'username': 'שם משתמש',
            'first_name': 'שם פרטי',
            'last_name': 'שם משפחה',
            'password1': 'סיסמא',
            'password2': 'אישור סיסמא',
        }


class CovidDataForm(forms.ModelForm):
    plate_details = forms.CharField(required=False)
    patient_details = forms.CharField(required=False)
    take_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',), label='תאריך לקיחה')
    get_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',), label='תאריך קבלה')

    class Meta:
        model = CovidData
        fields = '__all__'
        exclude = ['lab_code', 'lab_desc', 'tested_code', 'year_of_sticker', 'created_by', 'sender_code', 'method_code', 'method_desc', 'spec_code', 'spec_desc', 'result_date', 'sticker_number','result' ]
        labels = {
            'gender': "מין",
            'ID_num': 'ת"ז',
            'first_name': 'שם פרטי',
            'last_name': 'שם משפחה',
            'year_of_birth': 'שנת לידה',
            'internal_code': 'קוד פנימי',
            'internal_number': 'מספר פנימי',
            'section_code': 'קוד מדור מבצע',
            'section_desc': 'תאור מדור מבצע',
            'tested_desc': 'תאור גורם נבדק',
            'take_date': 'תאריך לקיחה',
            'get_date': 'תאריך קבלה',
            'remark': 'הערה',
            'id_type': 'סוג תעודה',
            'sender_name': 'שם גורם שולח',
            'sender_full_name': 'שם גורם שולח מלא',
            'result_test_corona': 'קוד תוצאה'
        }
        widgets = {
            'result_date': forms.DateInput(format="%m/%d/%Y"),
            'remark': forms.Textarea(attrs={'rows': 3, 'cols': 25}),
        }

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import CovidData
from.forms import CovidDataForm
from django.http import HttpResponse
from .resources import CovidResource
import csv
from django.forms.models import model_to_dict
from .forms import SignUpForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.contrib import messages
import datetime
from dal import autocomplete
from django.conf import settings
from django.db.models import Q
import os


def export_file(covid):
    data = model_to_dict(covid)

    del data['created_by']
    del data['exported']
    for key, value in data.items():

        if isinstance(value, datetime.date):
            date_string = value.strftime('%d%m%Y')
            data[key] = date_string
        if isinstance(value, int):
            data[key] = str(value)

        if value is None or value == '':
            data[key] = ' '

    filename = f"41997.Negifim.{data['result_date']}.{data['sticker_number']}.txt"
    del data['id']

    values = [value for value in data.values()]
    content = ';'.join(values)

    os.chdir(settings.EXPORT_STRING)
    with open(filename, 'w', encoding='windows-1255') as f:
        f.write(content)
        f.close()
        
        
def index(request):
    if request.user.is_authenticated:
        return redirect('search')
    return render(request, 'index.html')


class DeleteCovidView(DeleteView):
    model = CovidData
    success_url = reverse_lazy('list_forms')
    pk_url_kwarg = 'covid_pk'
    template_name = 'confirm_delete.html'

@login_required
def update_covid(request, covid_id):
    # get id's for next and previous objects if they exist
    covid = CovidData.objects.get(pk=covid_id)
    qset = list(CovidData.objects.all())
    obj_index = qset.index(covid)
    try:
        previous = qset[obj_index - 1]
    except IndexError:
        previous = None
    else:
        previous = previous.id
    try:
        next = qset[obj_index + 1]
    except IndexError:
        next = None
    else:
        next = next.id
    if obj_index == 0:
        previous = None

    if request.method == 'POST':
        form = CovidDataForm(request.POST, instance=covid)
        if form.is_valid():
            tz = form.cleaned_data['ID_num']
            # Validate that if field id_type is 0,1 that its only 9 digits and if it isnt prepend 0's until it is
            if form.cleaned_data['id_type'] in [0,1]:
                while len(tz) < 9:
                    tz = '0' + tz
            data = form.save(commit=False)
            data.result = data.get_result_test_corona_display()
            data.ID_num = tz
            data.save()
            return redirect('search')
        for field, error in form.errors.items():
            messages.warning(request, error)
        return redirect('update')
    form = CovidDataForm(instance=covid)
    return render(request, 'form_page.html', {'form': form, 'previous': previous, 'next': next, 'object': covid})

@login_required
def export(request, covid_id):
    covid = CovidData.objects.get(pk=covid_id)
    if covid.exported:
        messages.warning(request, 'הקובץ כבר ייוצא פעם אחת, נא לפנות למנהל המערכת.')
    elif not covid.result_test_corona:
        messages.warning(request, 'לקובץ אין שדה תוצאה תקינה, נא לתקן את השדה ולנסות לייצא שוב.')
        return redirect('search')
    else:
        export_file(covid)
        covid.exported = True
        covid.save()
        messages.success(request, 'קובץ בדיקה ייוצא בהצלחה')
    return redirect('search')



@login_required
def search_tz(request):
    objects = CovidData.objects.all().order_by('result_date')
    if request.method == 'POST':
        text = request.POST.get('search_tz')
        objects = CovidData.objects.filter(ID_num__icontains=text)
    return render(request, 'search.html', {'objects': objects})

@login_required
def search_date(request):
    objects = None
    if request.method == 'POST':
        date_string = request.POST.get('search_date')
        objects = CovidData.objects.filter(result_date=datetime.datetime.strptime(date_string, '%m/%d/%Y').date())
    return render(request, 'search.html', {'objects': objects})


@login_required
def search_sticker(request):
    objects = None
    if request.method == 'POST':
        data = request.POST.get('search_sticker').split('\\')
        sticker_num = data[1]
        sticker_date = data[0]
        objects = CovidData.objects.filter(sticker_number=sticker_num, result_date=datetime.datetime.strptime(sticker_date, '%m/%d/%Y').date())
    return render(request, 'search.html', {'objects': objects})

@login_required
def create_covid(request):
    if request.method == 'POST':
        form = CovidDataForm(request.POST)
        if form.is_valid():
            tz = form.cleaned_data['ID_num']
            # Validate that if field id_type is 0,1 that its only 9 digits and if it isnt prepend 0's until it is
            if form.cleaned_data['id_type'] in [0, 1]:
                while len(tz) < 9:
                    tz = '0' + tz

            # Get data from scanned barcode fields
            result_date_str = form.cleaned_data['plate_details'].split('_')[0]
            result_datetime = datetime.datetime.strptime(result_date_str, '%d-%m-%y')
            sticker_num = rf"{form.cleaned_data['patient_details']}".split('\\')[1]
            data = form.save(commit=False)
            data.created_by = request.user
            data.result_date = result_datetime
            data.sticker_number = sticker_num
            data.ID_num = tz
            data.result = data.get_result_test_corona_display()
            # data.result = data.result_test_corona.get_display_value()
            data.save()
            return redirect('search')
        for field, error in form.errors.items():
            messages.warning(request, error)
        return redirect('create')
    form = CovidDataForm()
    return render(request, 'new_form.html', {'form': form})

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="rtl">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
         <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <!-- Fengyuan Chen's Datepicker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <title>
        {% block title %}CovidGUI{% endblock %}
    </title>
    </head>

    <body>
    <div style="position: relative; min-height: 100vh;" >
        {% include 'partials/navbar.html' %}
        <div class="container mt-1" style="padding-bottom: 5rem;">
            {% if messages %}
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
              </div>
            {% endfor %}
        {% endif %}
            {% block content %}

            {% endblock %}
        </div>

    <footer style="position: absolute;  bottom: 0;  width: 100%;  height: 5rem;">
    <hr>
    <div class="row">
        <a href="{% static 'main/info.pdf' %}" class="col-1">הוראות הפעלה</a>
        <div class="col-5"></div>
        <h6 class="col-6">ייוצר ע"י אבי בוכמן ~אתרים פשוטים ונכונים</h6>
    </div>

</footer>
    </div>
    </body>
<script>
     var time = new Date().getTime();
     $(document.body).bind("mousemove keypress", function(e) {
         time = new Date().getTime();
     });

     function refresh() {
         if(new Date().getTime() - time >= 899000)
             alert('נותקת מהמערכת עקב חוסר פעילות של 15+ דקות, נא רענן עמוד זה');
         else
             setTimeout(refresh, 10000);
     }

     setTimeout(refresh, 10000);
</script>




</html>

main/templates/confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link" 
                       type="button" value="Cancel" 
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock %}

main/templates/form_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h5> פרטי טופס בדיקה</h5>
<form method="post" id="myForm" class="mb-5" autocomplete="off">
 <div class="row sticky-top ">
 <div class="col-6 d-flex justify-content-center">
  {% if previous %}
        <a href="{% url 'update' previous %}" class="btn btn-success">טופס קודם</a>
     {% endif %}
 </div>

 <div class="col-6 d-flex justify-content-center">

 <button type="submit" class="btn btn-primary">שמירת טופס</button>
 </div>
  <div class="col-3 d-flex justify-content-center">

     {% if next %}
        <a href="{% url 'update' next %}" class="btn btn-info">טופס הבא</a>
     {% endif %}
</div>

    </div>
    {% csrf_token %}
<div class="row">
     {% include 'temp.html' with form=form update=True %}
</div>

</form>

<script>
  $(function () {
    $("#id_take_date").datepicker();
  });
</script>
<script>
  $(function () {
    $("#id_get_date").datepicker();
  });
</script>
<script>
  $(function () {
    $("#id_result_date").datepicker();
  });
</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.AreYouSure/1.9.0/jquery.are-you-sure.min.js"></script>
    <script>
  $(function() {
    $('#myForm').areYouSure(
      {
        message: 'אם תעזוב עכשיו השינויים לא יישמרו, נא לשמור את הטופס על מנת שלא לאבד מידע'
      }
    );
  });

</script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/select2.css' %}" />
    <script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
    <link type="text/css" rel="{% static 'autocomplete_light/select2.css' %}">
    <script type="text/javascript" src="{% static 'vendor/select2/dist/js/select2.full.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/forward.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
    <h5 class="mb-5">ברוכים הבאים למערכת הזנת טפסי בדיקות </h5>
    <h6 class="mt-5">תמיכה טכנית בשמות משתמש וסיסמא <strong style="color: red">בהודעות בלבד!!</strong> 0505075980 אלעד אוסי </h6>
    <a href="{% url 'login' %}" class="ml-3 btn btn-primary">התחברות למערכת</a>
</div>
{% endblock %}

main/templates/midpage.html
{% extends 'base.html' %}
{% block content %}
     <a hidden href="{% url 'edit_form' cid %}" id="redirect" class="btn btn-info "></a>
    <a hidden href="{% url 'export' cid %}" id="download" class="btn btn-warning "></a>

    <script>

        async function delay(delayInms) {
      return new Promise(resolve  => {
        setTimeout(() => {
          resolve(2);
        }, delayInms);
      });
    }
    async function sample() {
      document.getElementById("download").click();
      console.log('waiting...')
      let delayres = await delay(3000);
      document.getElementById("redirect").click();
    }
    sample();
    </script>
{% endblock %}

main/templates/new_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h5>מילוי פרטי בדיקה</h5>

<form method="post" id="myForm" autocomplete="off">

    {% csrf_token %}
<div class="row">
    {% include 'temp.html' with form=form update=False %}
</div>
<div class="d-flex justify-content-between mb-5">
    <input class="btn btn-danger" type="button" value="ניקוי טופס" onClick="this.form.reset()" />
    <button type="submit" class="btn btn-primary">שמירת טופס</button>
</div>
</form>
{# <!-- Tempus Dominus Bootstrap 4 -->#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>#}

<script>
  $(function () {
    $("#id_take_date").datepicker();
  });
</script>

<script>
  $(function () {
    $("#id_get_date").datepicker();
  });
</script>
<script>
  $(function () {
    $("#id_result_date").datepicker();
  });
</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.AreYouSure/1.9.0/jquery.are-you-sure.min.js"></script>
    <script>
  $(function() {
    $('#myForm').areYouSure(
      {
        message: 'אם תעזוב עכשיו השינויים לא יישמרו, נא לשמור את הטופס על מנת שלא לאבד מידע'
      }
    );
  });

</script>

{% endblock %}

main/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>הרשמה</h1>
<form method="post">
    {% csrf_token %}
    {{ form | crispy }}

  <button type="submit" class="btn btn-primary">הרשמה</button>
</form>
{% endblock %}

main/templates/temp.html
<div class="row">
    {% if not update %}
    <div class="col-4 mt-2">
        {{ form.plate_details.errors }}
         <div class="float-right"><label for="{{ form.plate_details.id_for_label }}">מספר פלטה*:</label></div>
        {{ form.plate_details }}
    </div>
    <div class="col-4 mt-2">
        {{ form.patient_details.errors }}
        <div class="float-right"><label for="{{ form.patient_details.id_for_label }}">פרטי נבדק*:</label></div>
        {{ form.patient_details }}
    </div>
    <div class="col-4 mt-2"></div>
    {% endif %}
    <div class="col-4 mt-2">
        {{ form.id_type.errors }}
        <div class="float-right"><label for="{{ form.id_type.id_for_label }}">סוג תעודה*:</label></div>
        {{ form.id_type }}
    </div>
    <div class="col-4 mt-2">
        {{ form.ID_num.errors }}
        <div class="float-right"><label for="{{ form.ID_num.id_for_label }}">תעודת זהות*:</label></div>
        {{ form.ID_num }}
    </div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.gender.errors }}
        <div class="float-right"><label for="{{ form.gender.id_for_label }}">מין*:</label></div>
        {{ form.gender }}
    </div>
    <div class="col-4 mt-2">
        {{ form.year_of_birth.errors }}
        <div class="float-right"><label for="{{ form.year_of_birth.id_for_label }}">שנת לידה*:</label></div>
        {{ form.year_of_birth }}
    </div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.first_name.errors }}
        <div class="float-right"><label for="{{ form.first_name.id_for_label }}">שם פרטי*:</label></div>
        {{ form.first_name }}
    </div>
    <div class="col-4 mt-2">
        {{ form.last_name.errors }}
        <div class="float-right"><label for="{{ form.last_name.id_for_label }}">שם משפחה*:</label></div>
        {{ form.last_name }}
    </div>
    <div class="col-4 mt-2"></div>


    <div class="col-4 mt-2">
        {{ form.internal_code.errors }}
        <div class="float-right"><label for="{{ form.internal_code.id_for_label }}">קוד פנימי:</label></div>
        {{ form.internal_code }}
    </div>
    <div class="col-4 mt-2">
        {{ form.internal_number.errors }}
        <div class="float-right"><label for="{{ form.internal_number.id_for_label }}">מספר פנימי:</label></div>
        {{ form.internal_number }}
    </div>
        <div class="col-3"></div>

    <div class="col-4 mt-2">
        {{ form.section_code.errors }}
       <div class="float-right"><label for=" {{ form.section_code.id_for_label }}">קוד מדור מבצע*:</label></div>
        {{ form.section_code }}
    </div>
    <div class="col-4 mt-2">
        {{ form.section_desc.errors }}
        <div class="float-right"><label for="{{ form.section_desc.id_for_label }}">תאור מדור מבצע*:</label></div>
        {{ form.section_desc }}
    </div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.sender_name.errors }}
        <div class="float-right"><label for="{{ form.sender_name.id_for_label }}">שם גורם שולח:</label></div>
        {{ form.sender_name }}
    </div>
    <div class="col-4 mt-2">
        {{ form.sender_full_name.errors }}
        <div class="float-right"><label for="{{ form.sender_full_name.id_for_label }}">שם גורם שולח מלא:</label></div>
        {{ form.sender_full_name }}
    </div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.tested_desc.errors }}
        <div class="float-right"><label for="{{ form.tested_desc.id_for_label }}">תאור גורם נבדק*:</label></div>
        {{ form.tested_desc }}
    </div>
    <div class="col-4 mt-2"></div><div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.take_date.errors }}
        <div class="float-right"><label for="{{ form.take_date.id_for_label }}">תאריך לקיחה*:</label></div>
        {{ form.take_date }}
    </div>
    <div class="col-4 mt-2"></div><div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.get_date.errors }}
        <div class="float-right"><label for="{{ form.get_date.id_for_label }}">תאריך קבלה*:</label></div>
        {{ form.get_date }}
    </div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.result_test_corona.errors }}
        <div class="float-right"><label for="{{ form.result_test_corona.id_for_label }}">קוד תוצאה:</label></div>
        {{ form.result_test_corona }}
    </div>

    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2"></div>
    <div class="col-4 mt-2">
        {{ form.remark.errors }}
        <div class="float-right"><label for="{{ form.remark.id_for_label }}">הערה:</label></div>
        {{ form.remark }}
    </div>
    <div class="col-4 mt-2"></div><div class="col-4 mt-2"></div>
</div>

<script>
  $(function () {
    $("#id_take_date").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>

<script>
  $(function () {
    $("#id_get_date").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>
<script>
  $(function () {
    $("#id_result_date").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.AreYouSure/1.9.0/jquery.are-you-sure.min.js"></script>
    <script>
  $(function() {
    $('#myForm').areYouSure(
      {
        message: 'אם תעזוב עכשיו השינויים לא יישמרו, נא לשמור את הטופס על מנת שלא לאבד מידע'
      }
    );
  });

</script>